# packaging and caching assets in every environment.
package_assets: always

# When off, only the plain version of the asset will be written out,
# not the .gz alternative. Disable this if you don't plan on configuring
# your webserver to serve the static gzip alternatives.
# If you want to turn it on you might have to allows sending precompressed
# files with the “.gz” filename extension instead of regular files
# in your webserver, explaind in following link
# For nginx==> http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
# For apache==> http://httpd.apache.org/docs/2.0/mod/mod_deflate.html

gzip_assets: off

javascripts:
  canvas:
    - app/assets/javascripts/home/html5shim.js
    - app/assets/javascripts/home/latest_jquery.js
    - app/assets/javascripts/bootstrap.min.js
    - app/assets/javascripts/home/theme.js
    - app/assets/javascripts/home/index-slider.js
    - app/assets/javascripts/home/flexslider.js
    - app/assets/javascripts/jquery.popupoverlay.js
    - app/assets/javascripts/home/custom.js
    - app/assets/javascripts/home/courses.js

stylesheets:
  canvas:
    - app/assets/stylesheets/bootstrap.min.css
    - app/assets/stylesheets/home/bootstrap-overrides.css
    - app/assets/stylesheets/home/theme.css
    - app/assets/stylesheets/home/googleapi.css
    - app/assets/stylesheets/home/font.css
    - app/assets/stylesheets/home/index.css
    - app/assets/stylesheets/home/about.css
    - app/assets/stylesheets/home/flexslider.css
    - app/assets/stylesheets/home/contact.css
    - app/assets/stylesheets/home/animate.css
    - app/assets/stylesheets/home/custom.css
