app_name: "Pranic Healing - Ahmedabad"

default_password: 'india2014'

pagination:
  per_page: 10

payment:
  net_banking:
    bank_name: <%= ENV['BANK_NAME'] %>
    branch_name: <%= ENV['BRANCH_NAME'] %>
    account_name: <%= ENV['ACCOUNT_NAME'] %>
    account_number: <%= ENV['ACCOUNT_NUMBER'] %>
    ifsc: <%= ENV['IFSC'] %>

defaults:
  date_format_in_views: '%d/%m/%Y'

paperclip:
  style:
    medium: '300x300'
    thumb: '100x100'
  image_path: '/system/:class/:avatars/:id/:style/:basename.:extension'

mail:
  default_url_options:
    support_email: 'support@healersconnect.in'