app_name: "Pranic Healing - Ahmedabad"
brand_name: 'Pranic Healing'
default_password: 'india2014'

pagination:
  per_page: 10
  per_page_5: 5

events:
  paperclip: { path: "/home/healer/photos/events/:id/:style/:filename", url: "photos/events/:id/:style/:filename" }

event_gallery:
  paperclip: { path: "/home/healer/photos/events/:event_id/gallery/:id/:style/:filename", url: "photos/events/:event_id/gallery/:id/:style/:filename" }

event_schedule_gallery:
  paperclip: { path: "/home/healer/photos/event_schedule_gallery/:id/:style/:filename", url: "photos/event_schedule_gallery/:event_schedule_id/:id/:style/:filename" }

courses:
  paperclip: { path: "/home/healer/photos/courses/:id/:style/:filename", url: "photos/courses/:id/:style/:filename" }

payment:
  net_banking:
    bank_name: <%= ENV['BANK_NAME'] %>
    branch_name: <%= ENV['BRANCH_NAME'] %>
    account_name: <%= ENV['ACCOUNT_NAME'] %>
    account_number: <%= ENV['ACCOUNT_NUMBER'] %>
    ifsc: <%= ENV['IFSC'] %>

defaults:
  date_format_in_views: '%d/%m/%Y'

home_activities:
  paperclip:
    style:
      medium: '420x236'
      thumb_detail: '640x360'
    image_path: '/system/:class/:avatars/:id/:style/:basename.:extension'

paperclip:
  style:
    medium: '300x300'
    thumb: '100x100'
    activity:
      small: '55x55'
  image_path: '/system/:class/:avatars/:id/:style/:basename.:extension'

mail:
  default_url_options:
    support_email: 'support@healersconnect.in'